import { describe, expect, it } from "vitest";

import { IDEMPOTENCY_KEY_SCHEMA } from "@/lib/api/idempotency-key";

describe("IDEMPOTENCY_KEY_SCHEMA", () => {
  it("accepts a UUID v4 generated by uuidgen / crypto.randomUUID()", () => {
    const out = IDEMPOTENCY_KEY_SCHEMA.safeParse(
      "11dc68cb-2cf6-46e9-bf35-de39e551c0a3",
    );
    expect(out.success).toBe(true);
  });

  it("accepts a printable-ASCII short key", () => {
    expect(IDEMPOTENCY_KEY_SCHEMA.safeParse("key-abc-1").success).toBe(true);
  });

  it("rejects empty string", () => {
    const out = IDEMPOTENCY_KEY_SCHEMA.safeParse("");
    expect(out.success).toBe(false);
  });

  it("rejects > 128 chars", () => {
    const out = IDEMPOTENCY_KEY_SCHEMA.safeParse("a".repeat(129));
    expect(out.success).toBe(false);
  });

  it("rejects exactly 128 chars containing a control character", () => {
    const out = IDEMPOTENCY_KEY_SCHEMA.safeParse("a".repeat(127) + "\n");
    expect(out.success).toBe(false);
  });

  it("rejects embedded newline (log-poisoning vector)", () => {
    const out = IDEMPOTENCY_KEY_SCHEMA.safeParse("foo\nbar");
    expect(out.success).toBe(false);
    if (out.success) return;
    expect(out.error.issues[0]?.message).toMatch(/printable ASCII/);
  });

  it("rejects embedded null byte", () => {
    expect(IDEMPOTENCY_KEY_SCHEMA.safeParse("foo\0bar").success).toBe(false);
  });

  it("rejects tab character", () => {
    expect(IDEMPOTENCY_KEY_SCHEMA.safeParse("foo\tbar").success).toBe(false);
  });

  it("rejects non-ASCII Unicode characters", () => {
    expect(IDEMPOTENCY_KEY_SCHEMA.safeParse("café").success).toBe(false);
    expect(IDEMPOTENCY_KEY_SCHEMA.safeParse("钱包").success).toBe(false);
    expect(IDEMPOTENCY_KEY_SCHEMA.safeParse("🔑abc").success).toBe(false);
  });

  it("accepts 128 chars of pure ASCII", () => {
    expect(IDEMPOTENCY_KEY_SCHEMA.safeParse("a".repeat(128)).success).toBe(true);
  });

  it("accepts base64-shaped key", () => {
    expect(
      IDEMPOTENCY_KEY_SCHEMA.safeParse("dGVzdC1pZGVtcG90ZW5jeS1rZXk=").success,
    ).toBe(true);
  });
});
